server:
  port: 80
  servlet:
    context-path: /

# spring
spring:
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    # 超时(毫秒)
    timeout: 10000
    # 连接池配置
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间,-1为无限制
        max-wait: -1
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 0

# swagger 配置接口访问域名
swagger:
  host: http://ivfhg7.natappfree.cc