server:
  port: 80
  servlet:
    context-path: /

# spring
spring:
  # datasource
  datasource:
    password: 123456
  # redis
  redis:
    password:

# swagger 配置接口访问域名
swagger:
  host: localhost